"""empty message

Revision ID: 24270f525b16
Revises: a5cffa318ac2
Create Date: 2025-11-29 00:36:59.856174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24270f525b16'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tittle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
