"""empty message

Revision ID: b4b2b470d14e
Revises: e4e1d05e0e22
Create Date: 2025-11-29 05:21:34.028801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b2b470d14e'
down_revision = 'e4e1d05e0e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_comment_text_key', type_='unique')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_message_key', type_='unique')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_unique_constraint('post_title_key', ['title'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_unique_constraint('notification_message_key', ['message'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_unique_constraint('comment_comment_text_key', ['comment_text'])

    op.drop_table('follower')
    # ### end Alembic commands ###
